// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.20.0--rc2
// source: proto/gopackagesdriver.proto

package gopackagesdriverpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoadPackagesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Queries  []string `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
	LoadMode uint64   `protobuf:"varint,2,opt,name=load_mode,json=loadMode,proto3" json:"load_mode,omitempty"`
}

func (x *LoadPackagesRequest) Reset() {
	*x = LoadPackagesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gopackagesdriver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadPackagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadPackagesRequest) ProtoMessage() {}

func (x *LoadPackagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gopackagesdriver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadPackagesRequest.ProtoReflect.Descriptor instead.
func (*LoadPackagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_gopackagesdriver_proto_rawDescGZIP(), []int{0}
}

func (x *LoadPackagesRequest) GetQueries() []string {
	if x != nil {
		return x.Queries
	}
	return nil
}

func (x *LoadPackagesRequest) GetLoadMode() uint64 {
	if x != nil {
		return x.LoadMode
	}
	return 0
}

type LoadPackagesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RawJson string `protobuf:"bytes,1,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
}

func (x *LoadPackagesResponse) Reset() {
	*x = LoadPackagesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gopackagesdriver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadPackagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadPackagesResponse) ProtoMessage() {}

func (x *LoadPackagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gopackagesdriver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadPackagesResponse.ProtoReflect.Descriptor instead.
func (*LoadPackagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_gopackagesdriver_proto_rawDescGZIP(), []int{1}
}

func (x *LoadPackagesResponse) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

var File_proto_gopackagesdriver_proto protoreflect.FileDescriptor

var file_proto_gopackagesdriver_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67,
	0x65, 0x73, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10,
	0x67, 0x6f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72,
	0x22, 0x4c, 0x0a, 0x13, 0x4c, 0x6f, 0x61, 0x64, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x71, 0x75, 0x65, 0x72, 0x69,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x71, 0x75, 0x65, 0x72, 0x69, 0x65,
	0x73, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x22, 0x31,
	0x0a, 0x14, 0x4c, 0x6f, 0x61, 0x64, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x61, 0x77, 0x5f, 0x6a, 0x73,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x61, 0x77, 0x4a, 0x73, 0x6f,
	0x6e, 0x32, 0x7a, 0x0a, 0x17, 0x47, 0x6f, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x44,
	0x72, 0x69, 0x76, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5f, 0x0a, 0x0c,
	0x4c, 0x6f, 0x61, 0x64, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x12, 0x25, 0x2e, 0x67,
	0x6f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x2e,
	0x4c, 0x6f, 0x61, 0x64, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x67, 0x6f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73,
	0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x50, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x45, 0x5a,
	0x43, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x6e, 0x7a,
	0x6f, 0x6a, 0x69, 0x76, 0x65, 0x2f, 0x62, 0x61, 0x7a, 0x65, 0x6c, 0x67, 0x6f, 0x70, 0x61, 0x63,
	0x6b, 0x61, 0x67, 0x65, 0x73, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x67, 0x6f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x64, 0x72, 0x69, 0x76,
	0x65, 0x72, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_gopackagesdriver_proto_rawDescOnce sync.Once
	file_proto_gopackagesdriver_proto_rawDescData = file_proto_gopackagesdriver_proto_rawDesc
)

func file_proto_gopackagesdriver_proto_rawDescGZIP() []byte {
	file_proto_gopackagesdriver_proto_rawDescOnce.Do(func() {
		file_proto_gopackagesdriver_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_gopackagesdriver_proto_rawDescData)
	})
	return file_proto_gopackagesdriver_proto_rawDescData
}

var file_proto_gopackagesdriver_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_gopackagesdriver_proto_goTypes = []interface{}{
	(*LoadPackagesRequest)(nil),  // 0: gopackagesdriver.LoadPackagesRequest
	(*LoadPackagesResponse)(nil), // 1: gopackagesdriver.LoadPackagesResponse
}
var file_proto_gopackagesdriver_proto_depIdxs = []int32{
	0, // 0: gopackagesdriver.GoPackagesDriverService.LoadPackages:input_type -> gopackagesdriver.LoadPackagesRequest
	1, // 1: gopackagesdriver.GoPackagesDriverService.LoadPackages:output_type -> gopackagesdriver.LoadPackagesResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_gopackagesdriver_proto_init() }
func file_proto_gopackagesdriver_proto_init() {
	if File_proto_gopackagesdriver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_gopackagesdriver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadPackagesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gopackagesdriver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadPackagesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_gopackagesdriver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gopackagesdriver_proto_goTypes,
		DependencyIndexes: file_proto_gopackagesdriver_proto_depIdxs,
		MessageInfos:      file_proto_gopackagesdriver_proto_msgTypes,
	}.Build()
	File_proto_gopackagesdriver_proto = out.File
	file_proto_gopackagesdriver_proto_rawDesc = nil
	file_proto_gopackagesdriver_proto_goTypes = nil
	file_proto_gopackagesdriver_proto_depIdxs = nil
}
