// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0--rc2
// source: src/main/java/com/google/devtools/build/lib/bazel/debug/workspace_log.proto

package bazelworkspacelogpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Arguments       []string          `protobuf:"bytes,2,rep,name=arguments,proto3" json:"arguments,omitempty"`
	TimeoutSeconds  int32             `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	Environment     map[string]string `protobuf:"bytes,4,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Quiet           bool              `protobuf:"varint,5,opt,name=quiet,proto3" json:"quiet,omitempty"`
	OutputDirectory string            `protobuf:"bytes,6,opt,name=output_directory,json=outputDirectory,proto3" json:"output_directory,omitempty"`
}

func (x *ExecuteEvent) Reset() {
	*x = ExecuteEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteEvent) ProtoMessage() {}

func (x *ExecuteEvent) ProtoReflect() protoreflect.Message {
	mi := &file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteEvent.ProtoReflect.Descriptor instead.
func (*ExecuteEvent) Descriptor() ([]byte, []int) {
	return file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteEvent) GetArguments() []string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *ExecuteEvent) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ExecuteEvent) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *ExecuteEvent) GetQuiet() bool {
	if x != nil {
		return x.Quiet
	}
	return false
}

func (x *ExecuteEvent) GetOutputDirectory() string {
	if x != nil {
		return x.OutputDirectory
	}
	return ""
}

type DownloadEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url        []string `protobuf:"bytes,1,rep,name=url,proto3" json:"url,omitempty"`
	Output     string   `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Sha256     string   `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Executable bool     `protobuf:"varint,4,opt,name=executable,proto3" json:"executable,omitempty"`
	Integrity  string   `protobuf:"bytes,5,opt,name=integrity,proto3" json:"integrity,omitempty"`
}

func (x *DownloadEvent) Reset() {
	*x = DownloadEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadEvent) ProtoMessage() {}

func (x *DownloadEvent) ProtoReflect() protoreflect.Message {
	mi := &file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadEvent.ProtoReflect.Descriptor instead.
func (*DownloadEvent) Descriptor() ([]byte, []int) {
	return file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_rawDescGZIP(), []int{1}
}

func (x *DownloadEvent) GetUrl() []string {
	if x != nil {
		return x.Url
	}
	return nil
}

func (x *DownloadEvent) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *DownloadEvent) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *DownloadEvent) GetExecutable() bool {
	if x != nil {
		return x.Executable
	}
	return false
}

func (x *DownloadEvent) GetIntegrity() string {
	if x != nil {
		return x.Integrity
	}
	return ""
}

type ExtractEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Archive     string `protobuf:"bytes,1,opt,name=archive,proto3" json:"archive,omitempty"`
	Output      string `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	StripPrefix string `protobuf:"bytes,3,opt,name=strip_prefix,json=stripPrefix,proto3" json:"strip_prefix,omitempty"`
}

func (x *ExtractEvent) Reset() {
	*x = ExtractEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtractEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractEvent) ProtoMessage() {}

func (x *ExtractEvent) ProtoReflect() protoreflect.Message {
	mi := &file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractEvent.ProtoReflect.Descriptor instead.
func (*ExtractEvent) Descriptor() ([]byte, []int) {
	return file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_rawDescGZIP(), []int{2}
}

func (x *ExtractEvent) GetArchive() string {
	if x != nil {
		return x.Archive
	}
	return ""
}

func (x *ExtractEvent) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ExtractEvent) GetStripPrefix() string {
	if x != nil {
		return x.StripPrefix
	}
	return ""
}

type DownloadAndExtractEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url         []string `protobuf:"bytes,1,rep,name=url,proto3" json:"url,omitempty"`
	Output      string   `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Sha256      string   `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Type        string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	StripPrefix string   `protobuf:"bytes,5,opt,name=strip_prefix,json=stripPrefix,proto3" json:"strip_prefix,omitempty"`
	Integrity   string   `protobuf:"bytes,6,opt,name=integrity,proto3" json:"integrity,omitempty"`
}

func (x *DownloadAndExtractEvent) Reset() {
	*x = DownloadAndExtractEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadAndExtractEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadAndExtractEvent) ProtoMessage() {}

func (x *DownloadAndExtractEvent) ProtoReflect() protoreflect.Message {
	mi := &file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadAndExtractEvent.ProtoReflect.Descriptor instead.
func (*DownloadAndExtractEvent) Descriptor() ([]byte, []int) {
	return file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_rawDescGZIP(), []int{3}
}

func (x *DownloadAndExtractEvent) GetUrl() []string {
	if x != nil {
		return x.Url
	}
	return nil
}

func (x *DownloadAndExtractEvent) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *DownloadAndExtractEvent) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *DownloadAndExtractEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DownloadAndExtractEvent) GetStripPrefix() string {
	if x != nil {
		return x.StripPrefix
	}
	return ""
}

func (x *DownloadAndExtractEvent) GetIntegrity() string {
	if x != nil {
		return x.Integrity
	}
	return ""
}

type FileEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path       string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content    string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Executable bool   `protobuf:"varint,3,opt,name=executable,proto3" json:"executable,omitempty"`
}

func (x *FileEvent) Reset() {
	*x = FileEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEvent) ProtoMessage() {}

func (x *FileEvent) ProtoReflect() protoreflect.Message {
	mi := &file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEvent.ProtoReflect.Descriptor instead.
func (*FileEvent) Descriptor() ([]byte, []int) {
	return file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_rawDescGZIP(), []int{4}
}

func (x *FileEvent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *FileEvent) GetExecutable() bool {
	if x != nil {
		return x.Executable
	}
	return false
}

type ReadEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *ReadEvent) Reset() {
	*x = ReadEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadEvent) ProtoMessage() {}

func (x *ReadEvent) ProtoReflect() protoreflect.Message {
	mi := &file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadEvent.ProtoReflect.Descriptor instead.
func (*ReadEvent) Descriptor() ([]byte, []int) {
	return file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_rawDescGZIP(), []int{5}
}

func (x *ReadEvent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DeleteEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *DeleteEvent) Reset() {
	*x = DeleteEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEvent) ProtoMessage() {}

func (x *DeleteEvent) ProtoReflect() protoreflect.Message {
	mi := &file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEvent.ProtoReflect.Descriptor instead.
func (*DeleteEvent) Descriptor() ([]byte, []int) {
	return file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteEvent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type PatchEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PatchFile string `protobuf:"bytes,1,opt,name=patch_file,json=patchFile,proto3" json:"patch_file,omitempty"`
	Strip     int32  `protobuf:"varint,2,opt,name=strip,proto3" json:"strip,omitempty"`
}

func (x *PatchEvent) Reset() {
	*x = PatchEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchEvent) ProtoMessage() {}

func (x *PatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchEvent.ProtoReflect.Descriptor instead.
func (*PatchEvent) Descriptor() ([]byte, []int) {
	return file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_rawDescGZIP(), []int{7}
}

func (x *PatchEvent) GetPatchFile() string {
	if x != nil {
		return x.PatchFile
	}
	return ""
}

func (x *PatchEvent) GetStrip() int32 {
	if x != nil {
		return x.Strip
	}
	return 0
}

type OsEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OsEvent) Reset() {
	*x = OsEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OsEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OsEvent) ProtoMessage() {}

func (x *OsEvent) ProtoReflect() protoreflect.Message {
	mi := &file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OsEvent.ProtoReflect.Descriptor instead.
func (*OsEvent) Descriptor() ([]byte, []int) {
	return file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_rawDescGZIP(), []int{8}
}

type SymlinkEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Path   string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *SymlinkEvent) Reset() {
	*x = SymlinkEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SymlinkEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymlinkEvent) ProtoMessage() {}

func (x *SymlinkEvent) ProtoReflect() protoreflect.Message {
	mi := &file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymlinkEvent.ProtoReflect.Descriptor instead.
func (*SymlinkEvent) Descriptor() ([]byte, []int) {
	return file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_rawDescGZIP(), []int{9}
}

func (x *SymlinkEvent) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *SymlinkEvent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type TemplateEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path          string            `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Template      string            `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	Substitutions map[string]string `protobuf:"bytes,3,rep,name=substitutions,proto3" json:"substitutions,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Executable    bool              `protobuf:"varint,4,opt,name=executable,proto3" json:"executable,omitempty"`
}

func (x *TemplateEvent) Reset() {
	*x = TemplateEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateEvent) ProtoMessage() {}

func (x *TemplateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateEvent.ProtoReflect.Descriptor instead.
func (*TemplateEvent) Descriptor() ([]byte, []int) {
	return file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_rawDescGZIP(), []int{10}
}

func (x *TemplateEvent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TemplateEvent) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *TemplateEvent) GetSubstitutions() map[string]string {
	if x != nil {
		return x.Substitutions
	}
	return nil
}

func (x *TemplateEvent) GetExecutable() bool {
	if x != nil {
		return x.Executable
	}
	return false
}

type WhichEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Program string `protobuf:"bytes,1,opt,name=program,proto3" json:"program,omitempty"`
}

func (x *WhichEvent) Reset() {
	*x = WhichEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhichEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhichEvent) ProtoMessage() {}

func (x *WhichEvent) ProtoReflect() protoreflect.Message {
	mi := &file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhichEvent.ProtoReflect.Descriptor instead.
func (*WhichEvent) Descriptor() ([]byte, []int) {
	return file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_rawDescGZIP(), []int{11}
}

func (x *WhichEvent) GetProgram() string {
	if x != nil {
		return x.Program
	}
	return ""
}

type WorkspaceEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location string `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Rule     string `protobuf:"bytes,2,opt,name=rule,proto3" json:"rule,omitempty"`
	// Types that are assignable to Event:
	//	*WorkspaceEvent_ExecuteEvent
	//	*WorkspaceEvent_DownloadEvent
	//	*WorkspaceEvent_DownloadAndExtractEvent
	//	*WorkspaceEvent_FileEvent
	//	*WorkspaceEvent_OsEvent
	//	*WorkspaceEvent_SymlinkEvent
	//	*WorkspaceEvent_TemplateEvent
	//	*WorkspaceEvent_WhichEvent
	//	*WorkspaceEvent_ExtractEvent
	//	*WorkspaceEvent_ReadEvent
	//	*WorkspaceEvent_DeleteEvent
	//	*WorkspaceEvent_PatchEvent
	Event isWorkspaceEvent_Event `protobuf_oneof:"event"`
}

func (x *WorkspaceEvent) Reset() {
	*x = WorkspaceEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkspaceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceEvent) ProtoMessage() {}

func (x *WorkspaceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceEvent.ProtoReflect.Descriptor instead.
func (*WorkspaceEvent) Descriptor() ([]byte, []int) {
	return file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_rawDescGZIP(), []int{12}
}

func (x *WorkspaceEvent) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *WorkspaceEvent) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (m *WorkspaceEvent) GetEvent() isWorkspaceEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *WorkspaceEvent) GetExecuteEvent() *ExecuteEvent {
	if x, ok := x.GetEvent().(*WorkspaceEvent_ExecuteEvent); ok {
		return x.ExecuteEvent
	}
	return nil
}

func (x *WorkspaceEvent) GetDownloadEvent() *DownloadEvent {
	if x, ok := x.GetEvent().(*WorkspaceEvent_DownloadEvent); ok {
		return x.DownloadEvent
	}
	return nil
}

func (x *WorkspaceEvent) GetDownloadAndExtractEvent() *DownloadAndExtractEvent {
	if x, ok := x.GetEvent().(*WorkspaceEvent_DownloadAndExtractEvent); ok {
		return x.DownloadAndExtractEvent
	}
	return nil
}

func (x *WorkspaceEvent) GetFileEvent() *FileEvent {
	if x, ok := x.GetEvent().(*WorkspaceEvent_FileEvent); ok {
		return x.FileEvent
	}
	return nil
}

func (x *WorkspaceEvent) GetOsEvent() *OsEvent {
	if x, ok := x.GetEvent().(*WorkspaceEvent_OsEvent); ok {
		return x.OsEvent
	}
	return nil
}

func (x *WorkspaceEvent) GetSymlinkEvent() *SymlinkEvent {
	if x, ok := x.GetEvent().(*WorkspaceEvent_SymlinkEvent); ok {
		return x.SymlinkEvent
	}
	return nil
}

func (x *WorkspaceEvent) GetTemplateEvent() *TemplateEvent {
	if x, ok := x.GetEvent().(*WorkspaceEvent_TemplateEvent); ok {
		return x.TemplateEvent
	}
	return nil
}

func (x *WorkspaceEvent) GetWhichEvent() *WhichEvent {
	if x, ok := x.GetEvent().(*WorkspaceEvent_WhichEvent); ok {
		return x.WhichEvent
	}
	return nil
}

func (x *WorkspaceEvent) GetExtractEvent() *ExtractEvent {
	if x, ok := x.GetEvent().(*WorkspaceEvent_ExtractEvent); ok {
		return x.ExtractEvent
	}
	return nil
}

func (x *WorkspaceEvent) GetReadEvent() *ReadEvent {
	if x, ok := x.GetEvent().(*WorkspaceEvent_ReadEvent); ok {
		return x.ReadEvent
	}
	return nil
}

func (x *WorkspaceEvent) GetDeleteEvent() *DeleteEvent {
	if x, ok := x.GetEvent().(*WorkspaceEvent_DeleteEvent); ok {
		return x.DeleteEvent
	}
	return nil
}

func (x *WorkspaceEvent) GetPatchEvent() *PatchEvent {
	if x, ok := x.GetEvent().(*WorkspaceEvent_PatchEvent); ok {
		return x.PatchEvent
	}
	return nil
}

type isWorkspaceEvent_Event interface {
	isWorkspaceEvent_Event()
}

type WorkspaceEvent_ExecuteEvent struct {
	ExecuteEvent *ExecuteEvent `protobuf:"bytes,3,opt,name=execute_event,json=executeEvent,proto3,oneof"`
}

type WorkspaceEvent_DownloadEvent struct {
	DownloadEvent *DownloadEvent `protobuf:"bytes,4,opt,name=download_event,json=downloadEvent,proto3,oneof"`
}

type WorkspaceEvent_DownloadAndExtractEvent struct {
	DownloadAndExtractEvent *DownloadAndExtractEvent `protobuf:"bytes,5,opt,name=download_and_extract_event,json=downloadAndExtractEvent,proto3,oneof"`
}

type WorkspaceEvent_FileEvent struct {
	FileEvent *FileEvent `protobuf:"bytes,6,opt,name=file_event,json=fileEvent,proto3,oneof"`
}

type WorkspaceEvent_OsEvent struct {
	OsEvent *OsEvent `protobuf:"bytes,7,opt,name=os_event,json=osEvent,proto3,oneof"`
}

type WorkspaceEvent_SymlinkEvent struct {
	SymlinkEvent *SymlinkEvent `protobuf:"bytes,8,opt,name=symlink_event,json=symlinkEvent,proto3,oneof"`
}

type WorkspaceEvent_TemplateEvent struct {
	TemplateEvent *TemplateEvent `protobuf:"bytes,9,opt,name=template_event,json=templateEvent,proto3,oneof"`
}

type WorkspaceEvent_WhichEvent struct {
	WhichEvent *WhichEvent `protobuf:"bytes,10,opt,name=which_event,json=whichEvent,proto3,oneof"`
}

type WorkspaceEvent_ExtractEvent struct {
	ExtractEvent *ExtractEvent `protobuf:"bytes,11,opt,name=extract_event,json=extractEvent,proto3,oneof"`
}

type WorkspaceEvent_ReadEvent struct {
	ReadEvent *ReadEvent `protobuf:"bytes,12,opt,name=read_event,json=readEvent,proto3,oneof"`
}

type WorkspaceEvent_DeleteEvent struct {
	DeleteEvent *DeleteEvent `protobuf:"bytes,13,opt,name=delete_event,json=deleteEvent,proto3,oneof"`
}

type WorkspaceEvent_PatchEvent struct {
	PatchEvent *PatchEvent `protobuf:"bytes,14,opt,name=patch_event,json=patchEvent,proto3,oneof"`
}

func (*WorkspaceEvent_ExecuteEvent) isWorkspaceEvent_Event() {}

func (*WorkspaceEvent_DownloadEvent) isWorkspaceEvent_Event() {}

func (*WorkspaceEvent_DownloadAndExtractEvent) isWorkspaceEvent_Event() {}

func (*WorkspaceEvent_FileEvent) isWorkspaceEvent_Event() {}

func (*WorkspaceEvent_OsEvent) isWorkspaceEvent_Event() {}

func (*WorkspaceEvent_SymlinkEvent) isWorkspaceEvent_Event() {}

func (*WorkspaceEvent_TemplateEvent) isWorkspaceEvent_Event() {}

func (*WorkspaceEvent_WhichEvent) isWorkspaceEvent_Event() {}

func (*WorkspaceEvent_ExtractEvent) isWorkspaceEvent_Event() {}

func (*WorkspaceEvent_ReadEvent) isWorkspaceEvent_Event() {}

func (*WorkspaceEvent_DeleteEvent) isWorkspaceEvent_Event() {}

func (*WorkspaceEvent_PatchEvent) isWorkspaceEvent_Event() {}

var File_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto protoreflect.FileDescriptor

var file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_rawDesc = []byte{
	0x0a, 0x4b, 0x73, 0x72, 0x63, 0x2f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x6a, 0x61, 0x76, 0x61, 0x2f,
	0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x64, 0x65, 0x76, 0x74, 0x6f,
	0x6f, 0x6c, 0x73, 0x2f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2f, 0x6c, 0x69, 0x62, 0x2f, 0x62, 0x61,
	0x7a, 0x65, 0x6c, 0x2f, 0x64, 0x65, 0x62, 0x75, 0x67, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x77,
	0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x22, 0xa6, 0x02, 0x0a,
	0x0c, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x09, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x74,
	0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x53, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x73, 0x12, 0x4e, 0x0a, 0x0b, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d,
	0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x77, 0x6f, 0x72, 0x6b,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65,
	0x6e, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x69, 0x65, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x71, 0x75, 0x69, 0x65, 0x74, 0x12, 0x29, 0x0a, 0x10, 0x6f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x5f, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x44, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x79, 0x1a, 0x3e, 0x0a, 0x10, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e,
	0x6d, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x8f, 0x01, 0x0a, 0x0d, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f,
	0x61, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x68, 0x61, 0x32, 0x35, 0x36, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x68, 0x61, 0x32, 0x35, 0x36, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x65,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x74,
	0x65, 0x67, 0x72, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e,
	0x74, 0x65, 0x67, 0x72, 0x69, 0x74, 0x79, 0x22, 0x63, 0x0a, 0x0c, 0x45, 0x78, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x72, 0x63, 0x68, 0x69,
	0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x74, 0x72,
	0x69, 0x70, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x73, 0x74, 0x72, 0x69, 0x70, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x22, 0xb0, 0x01, 0x0a,
	0x17, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x6e, 0x64, 0x45, 0x78, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x68, 0x61, 0x32, 0x35, 0x36, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x68, 0x61, 0x32, 0x35, 0x36, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x21,
	0x0a, 0x0c, 0x73, 0x74, 0x72, 0x69, 0x70, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x70, 0x50, 0x72, 0x65, 0x66, 0x69,
	0x78, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x69, 0x74, 0x79, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x69, 0x74, 0x79, 0x22,
	0x59, 0x0a, 0x09, 0x46, 0x69, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a,
	0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x1f, 0x0a, 0x09, 0x52, 0x65,
	0x61, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x21, 0x0a, 0x0b, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x41,
	0x0a, 0x0a, 0x50, 0x61, 0x74, 0x63, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x70, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x70, 0x61, 0x74, 0x63, 0x68, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x74, 0x72, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x72, 0x69,
	0x70, 0x22, 0x09, 0x0a, 0x07, 0x4f, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x3a, 0x0a, 0x0c,
	0x53, 0x79, 0x6d, 0x6c, 0x69, 0x6e, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0xf8, 0x01, 0x0a, 0x0d, 0x54, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x1a,
	0x0a, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x55, 0x0a, 0x0d, 0x73, 0x75,
	0x62, 0x73, 0x74, 0x69, 0x74, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x2f, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x6c, 0x6f,
	0x67, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e,
	0x53, 0x75, 0x62, 0x73, 0x74, 0x69, 0x74, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x0d, 0x73, 0x75, 0x62, 0x73, 0x74, 0x69, 0x74, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x61, 0x62, 0x6c,
	0x65, 0x1a, 0x40, 0x0a, 0x12, 0x53, 0x75, 0x62, 0x73, 0x74, 0x69, 0x74, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0x26, 0x0a, 0x0a, 0x57, 0x68, 0x69, 0x63, 0x68, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x22, 0xf2, 0x06, 0x0a, 0x0e,
	0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x75,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x75, 0x6c, 0x65, 0x12, 0x42,
	0x0a, 0x0d, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x48, 0x00, 0x52, 0x0c, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x12, 0x45, 0x0a, 0x0e, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x77, 0x6f, 0x72,
	0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c,
	0x6f, 0x61, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0d, 0x64, 0x6f, 0x77, 0x6e,
	0x6c, 0x6f, 0x61, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x65, 0x0a, 0x1a, 0x64, 0x6f, 0x77,
	0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x61, 0x6e, 0x64, 0x5f, 0x65, 0x78, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e,
	0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x44, 0x6f,
	0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x6e, 0x64, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x17, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61,
	0x64, 0x41, 0x6e, 0x64, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x39, 0x0a, 0x0a, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00,
	0x52, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x33, 0x0a, 0x08, 0x6f,
	0x73, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x4f, 0x73,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x07, 0x6f, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x42, 0x0a, 0x0d, 0x73, 0x79, 0x6d, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x53, 0x79, 0x6d, 0x6c, 0x69, 0x6e, 0x6b, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0c, 0x73, 0x79, 0x6d, 0x6c, 0x69, 0x6e, 0x6b, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x45, 0x0a, 0x0e, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x77,
	0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x54, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0d, 0x74, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x3c, 0x0a, 0x0b, 0x77,
	0x68, 0x69, 0x63, 0x68, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67,
	0x2e, 0x57, 0x68, 0x69, 0x63, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x77,
	0x68, 0x69, 0x63, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x42, 0x0a, 0x0d, 0x65, 0x78, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67,
	0x2e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52,
	0x0c, 0x65, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x39, 0x0a,
	0x0a, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x6c, 0x6f,
	0x67, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x09, 0x72,
	0x65, 0x61, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x3f, 0x0a, 0x0c, 0x64, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x3c, 0x0a, 0x0b, 0x70, 0x61, 0x74,
	0x63, 0x68, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x50,
	0x61, 0x74, 0x63, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x70, 0x61, 0x74,
	0x63, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x42, 0x07, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x42, 0x8b, 0x01, 0x0a, 0x2f, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x64, 0x65, 0x76, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2e, 0x6c,
	0x69, 0x62, 0x2e, 0x62, 0x61, 0x7a, 0x65, 0x6c, 0x2e, 0x64, 0x65, 0x62, 0x75, 0x67, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x42, 0x12, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x4c,
	0x6f, 0x67, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x5a, 0x44, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x6e, 0x7a, 0x6f, 0x6a, 0x69, 0x76, 0x65, 0x2f, 0x62,
	0x61, 0x7a, 0x65, 0x6c, 0x67, 0x6f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x64, 0x72,
	0x69, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x61, 0x7a, 0x65, 0x6c,
	0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x6c, 0x6f, 0x67, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_rawDescOnce sync.Once
	file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_rawDescData = file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_rawDesc
)

func file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_rawDescGZIP() []byte {
	file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_rawDescOnce.Do(func() {
		file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_rawDescData)
	})
	return file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_rawDescData
}

var file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_goTypes = []interface{}{
	(*ExecuteEvent)(nil),            // 0: workspace_log.ExecuteEvent
	(*DownloadEvent)(nil),           // 1: workspace_log.DownloadEvent
	(*ExtractEvent)(nil),            // 2: workspace_log.ExtractEvent
	(*DownloadAndExtractEvent)(nil), // 3: workspace_log.DownloadAndExtractEvent
	(*FileEvent)(nil),               // 4: workspace_log.FileEvent
	(*ReadEvent)(nil),               // 5: workspace_log.ReadEvent
	(*DeleteEvent)(nil),             // 6: workspace_log.DeleteEvent
	(*PatchEvent)(nil),              // 7: workspace_log.PatchEvent
	(*OsEvent)(nil),                 // 8: workspace_log.OsEvent
	(*SymlinkEvent)(nil),            // 9: workspace_log.SymlinkEvent
	(*TemplateEvent)(nil),           // 10: workspace_log.TemplateEvent
	(*WhichEvent)(nil),              // 11: workspace_log.WhichEvent
	(*WorkspaceEvent)(nil),          // 12: workspace_log.WorkspaceEvent
	nil,                             // 13: workspace_log.ExecuteEvent.EnvironmentEntry
	nil,                             // 14: workspace_log.TemplateEvent.SubstitutionsEntry
}
var file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_depIdxs = []int32{
	13, // 0: workspace_log.ExecuteEvent.environment:type_name -> workspace_log.ExecuteEvent.EnvironmentEntry
	14, // 1: workspace_log.TemplateEvent.substitutions:type_name -> workspace_log.TemplateEvent.SubstitutionsEntry
	0,  // 2: workspace_log.WorkspaceEvent.execute_event:type_name -> workspace_log.ExecuteEvent
	1,  // 3: workspace_log.WorkspaceEvent.download_event:type_name -> workspace_log.DownloadEvent
	3,  // 4: workspace_log.WorkspaceEvent.download_and_extract_event:type_name -> workspace_log.DownloadAndExtractEvent
	4,  // 5: workspace_log.WorkspaceEvent.file_event:type_name -> workspace_log.FileEvent
	8,  // 6: workspace_log.WorkspaceEvent.os_event:type_name -> workspace_log.OsEvent
	9,  // 7: workspace_log.WorkspaceEvent.symlink_event:type_name -> workspace_log.SymlinkEvent
	10, // 8: workspace_log.WorkspaceEvent.template_event:type_name -> workspace_log.TemplateEvent
	11, // 9: workspace_log.WorkspaceEvent.which_event:type_name -> workspace_log.WhichEvent
	2,  // 10: workspace_log.WorkspaceEvent.extract_event:type_name -> workspace_log.ExtractEvent
	5,  // 11: workspace_log.WorkspaceEvent.read_event:type_name -> workspace_log.ReadEvent
	6,  // 12: workspace_log.WorkspaceEvent.delete_event:type_name -> workspace_log.DeleteEvent
	7,  // 13: workspace_log.WorkspaceEvent.patch_event:type_name -> workspace_log.PatchEvent
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_init() }
func file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_init() {
	if File_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExtractEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadAndExtractEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatchEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OsEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SymlinkEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhichEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkspaceEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes[12].OneofWrappers = []interface{}{
		(*WorkspaceEvent_ExecuteEvent)(nil),
		(*WorkspaceEvent_DownloadEvent)(nil),
		(*WorkspaceEvent_DownloadAndExtractEvent)(nil),
		(*WorkspaceEvent_FileEvent)(nil),
		(*WorkspaceEvent_OsEvent)(nil),
		(*WorkspaceEvent_SymlinkEvent)(nil),
		(*WorkspaceEvent_TemplateEvent)(nil),
		(*WorkspaceEvent_WhichEvent)(nil),
		(*WorkspaceEvent_ExtractEvent)(nil),
		(*WorkspaceEvent_ReadEvent)(nil),
		(*WorkspaceEvent_DeleteEvent)(nil),
		(*WorkspaceEvent_PatchEvent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_goTypes,
		DependencyIndexes: file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_depIdxs,
		MessageInfos:      file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_msgTypes,
	}.Build()
	File_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto = out.File
	file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_rawDesc = nil
	file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_goTypes = nil
	file_src_main_java_com_google_devtools_build_lib_bazel_debug_workspace_log_proto_depIdxs = nil
}
